# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  build:
    docker: circleci/node:12

  working_directory: ~/vue-ts-admin-template

  steps:
      - checkout

      # Download dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - run: yarn lint

      - run: yarn test:unit

      - run: yarn build

      # Cache dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}